# docker-proxygen .travis.yml
#
# Builds docker-proxygen images on Travis CI
#
# https://travis-ci.org/neomantra/docker-proxygen
#
# Master will build with Docker tag:
#   neomantra/proxygen:latest
#   neomantra/proxygen:latest-oo<onload-version>
#
# Releases should be tagged in git as:
#   neomantra/proxygen:<tag-version> 
#   neomantra/proxygen:<tag-version>-oo<onload-version>
#
# Travis Environment Variables:
#   DOCKER_ORG
#   DOCKER_USERNAME
#   DOCKER_PASSWORD
#

language: bash

sudo: required

services:
  - docker

env:
  - PROXYGEN_BUILD_FROM=neomantra/onload:201811-cosmic-nozf
  - PROXYGEN_BUILD_FROM=neomantra/onload:201811-u1-cosmic-nozf
  - PROXYGEN_BUILD_FROM=neomantra/onload:201811-u1-disco-nozf
  - PROXYGEN_BUILD_FROM=neomantra/onloadzf:201811-cosmic
  - PROXYGEN_BUILD_FROM=neomantra/onloadzf:201811-u1-cosmic
  - PROXYGEN_BUILD_FROM=neomantra/onloadzf:201811-u1-disco
  - PROXYGEN_BUILD_FROM=ubuntu:cosmic
  - PROXYGEN_BUILD_FROM=ubuntu:disco


script:
  - if [[ "$TRAVIS_BRANCH" == "master" ]] ; then
      IMAGE_TAG_SUFFIX=$(echo "$PROXYGEN_BUILD_FROM" | sed -e '/^neomantra\/onload\(.*\):\([0-9u-]*\)-cosmic\(.*\)/!d;s//-oo\1\2/' ) ;
      PUSH_DEST="$DOCKER_ORG/proxygen:latest$IMAGE_TAG_SUFFIX" ;
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
      docker build -t proxygen-master -t $PUSH_DEST --cache-from $PUSH_DEST --build-arg J_LEVEL=2 --build-arg PROXYGEN_BUILD_FROM=${PROXYGEN_BUILD_FROM} . ;
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
      docker push $PUSH_DEST ;
    fi
  - if [[ "$TRAVIS_TAG" ]] ; then
      IMAGE_TAG_SUFFIX=$(echo "$PROXYGEN_BUILD_FROM" | sed -e '/^neomantra\/onload\(.*\):\([0-9u-]*\)-cosmic\(.*\)/!d;s//-oo\1\2/' ) ;
      PUSH_DEST="$DOCKER_ORG/proxygen:$TRAVIS_TAG$IMAGE_TAG_SUFFIX" ;
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
      docker build -t proxygen-tag -t $PUSH_DEST --cache-from $PUSH_DEST --build-arg J_LEVEL=2 --build-arg PROXYGEN_BUILD_FROM=${PROXYGEN_BUILD_FROM} --build-arg COMMON_VERSION=$TRAVIS_TAG . ;
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
      docker push $PUSH_DEST ;
    fi
