# docker-proxygen .travis.yml
#
# Builds docker-proxygen images on Travis CI
#
# https://travis-ci.org/neomantra/docker-proxygen
#
# Master will build with Docker tag:
#   neomantra/proxygen:latest
#   neomantra/proxygen:latest-oo<onload-version>
#
# Releases should be tagged in git as:
#   neomantra/proxygen:<tag-version> 
#   neomantra/proxygen:<tag-version>-oo<onload-version>
#
# Travis Environment Variables:
#   DOCKER_ORG
#   DOCKER_USERNAME
#   DOCKER_PASSWORD
#

language: bash

sudo: required

services:
  - docker

matrix:
  include:
  - env:
    - PROXYGEN_BUILD_FROM=neomantra/onload:201811-cosmic-nozf
    - IMAGE_TAG_SUFFIX=-oo201811-cosmic
  - env:
    - PROXYGEN_BUILD_FROM=neomantra/onload:201811-u1-cosmic-nozf
    - IMAGE_TAG_SUFFIX=-oo201811-u1-cosmic
  - env:
    - PROXYGEN_BUILD_FROM=neomantra/onload:201811-u1-disco-nozf
    - IMAGE_TAG_SUFFIX=-oo201811-u1-disco
  - env:
    - PROXYGEN_BUILD_FROM=neomantra/onloadzf:201811-cosmic
    - IMAGE_TAG_SUFFIX=-oozf201811-disco
  - env:
    - PROXYGEN_BUILD_FROM=neomantra/onloadzf:201811-u1-cosmic
    - IMAGE_TAG_SUFFIX=-oozf201811-u1-cosmic
  - env:
    - PROXYGEN_BUILD_FROM=neomantra/onloadzf:201811-u1-disco
    - IMAGE_TAG_SUFFIX=-oozf201811-u1-disco
  - env:
    - PROXYGEN_BUILD_FROM=ubuntu:cosmic
    - IMAGE_TAG_SUFFIX=-cosmic
  - env:
    - PROXYGEN_BUILD_FROM=ubuntu:disco
    - IMAGE_TAG_SUFFIX=-disco

script:
  - if [[ "$TRAVIS_BRANCH" == "master" ]] ; then
      PUSH_DEST="$DOCKER_ORG/proxygen:latest$IMAGE_TAG_SUFFIX" ;
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
      docker build -t proxygen-master -t $PUSH_DEST --cache-from $PUSH_DEST --build-arg J_LEVEL=2 --build-arg PROXYGEN_BUILD_FROM=${PROXYGEN_BUILD_FROM} . ;
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
      docker push $PUSH_DEST ;
      if [[ "$TRAVIS_TAG" ]] ; then
        TAG_PUSH_DEST="$DOCKER_ORG/proxygen:$TRAVIS_TAG$IMAGE_TAG_SUFFIX" ;
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
        docker build -t proxygen-tag -t $TAG_PUSH_DEST --cache-from $PUSH_DEST --build-arg J_LEVEL=2 --build-arg PROXYGEN_BUILD_FROM=${PROXYGEN_BUILD_FROM} --build-arg COMMON_VERSION=$TRAVIS_TAG . ;
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
        docker push $TAG_PUSH_DEST ;
      fi ;
    fi
